service: talk-to
disabledDeprecations:
  - CLI_DEPLOY_FUNCTION_OPTION_V3
  - CLI_OPTIONS_BEFORE_COMMAND
  - MISSING_COMMANDS_OR_OPTIONS_AT_CONSTRUCTION
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*' 
  environment:
    JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f

    DB_CONNECTION_HOST: mysqlserver.ctbhjnsyyeyu.us-east-1.rds.amazonaws.com
    DB_CONNECTION_PORT: 3306
    DB_CONNECTION_USERNAME: admin
    DB_CONNECTION_PASSWORD: 2589a04e693ddd7679d83bd90a09dcbd
    MONGO_HOST:  mongodb+srv://weton01:Dragonite1@professor.yrdup.mongodb.net/flat?authSource=admin&replicaSet=atlas-m1fn1c-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true

    GOOGLE_AUTH_CLIENT_ID: 193865804446-0no96b25i8dgqso79uh1ar5jni2n44j6.apps.googleusercontent.com
    GOOGLE_AUTH_CLIENT_SECRET: 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
    FACEBOOK_AUTH_CLIENT_ID: 1003471433904383
    FACEBOOK_AUTH_CLIENT_SECRET: 440be562ea1d7916e1c0ff385c77c08a
    REDIRECT_URL: http://localhost:3000

    TWACCOUNTSID: AC381988ce79fbc63d0a0f813126b42511
    TWAUTHTOKEN: 7401a0311a51ecc41de2ee1ecf6b8fce
    TWSERVICESID: VAdc9dd6a065d757b61fb4b38ddbf49854
    TWSENDER: +18325328071

    MAILER_TRANSPORT_HOST: smtp.mailtrap.io
    MAILER_TRANSPORT_PORT: 2525
    MAILER_TRANSPORT_AUTH_USER: bfed0bddaaa901
    MAILER_TRANSPORT_AUTH_PASS: 34f539bbd98320
    MAILER_MAIL_FROM: lich@lichdata.com

    AWS_KEY: AKIAYXQH4BSB232TJJY7
    AWS_ACCESS_SECRET_KEY: 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
    AWS_BUCKER_NAME: flora-express-images
    AWS_IMAGES_BUCKET_FOLDER_NAME: generic-shop
    NODE_ENV: production
 
functions:
  auth:
    handler: ./dist/apps/auth/main.handler
    events:
      - http:
          method: ANY
          path: /auth
      - http:
          method: ANY
          path: '/auth/{proxy+}'
  category:
    handler: ./dist/apps/category/main.handler
    events:
      - http:
          method: ANY
          path: /category
      - http:
          method: ANY
          path: '/category/{proxy+}'
  address:
    handler: ./dist/apps/address/main.handler
    events:
      - http:
          method: ANY
          path: /address
      - http:
          method: ANY
          path: '/address/{proxy+}'
  credit-card:
    handler: ./dist/apps/credit-card/main.handler
    events:
      - http:
          method: ANY
          path: /credit-card
      - http:
          method: ANY
          path: '/credit-card/{proxy+}'
  brand:
    handler: ./dist/apps/brand/main.handler
    events:
      - http:
          method: ANY
          path: /brand
      - http:
          method: ANY
          path: '/brand/{proxy+}'
  tag:
    handler: ./dist/apps/tag/main.handler
    events:
      - http:
          method: ANY
          path: /tag
      - http:
          method: ANY
          path: '/tag/{proxy+}'
  product:
    handler: ./dist/apps/product/main.handler
    events:
      - http:
          method: ANY
          path: /product
      - http:
          method: ANY
          path: '/product/{proxy+}'
  variation:
    handler: ./dist/apps/variation/main.handler
    events:
      - http:
          method: ANY
          path: /variation
      - http:
          method: ANY
          path: '/variation/{proxy+}'
  comment:
    handler: ./dist/apps/comment/main.handler
    events:
      - http:
          method: ANY
          path: /comment
      - http:
          method: ANY
          path: '/comment/{proxy+}'

  flat:
    handler: ./dist/apps/flat/main.handler
    events:
      - http:
          method: ANY
          path: /flat
      - http:
          method: ANY
          path: '/flat/{proxy+}'
    
