service: sindria
disabledDeprecations:
  - CLI_DEPLOY_FUNCTION_OPTION_V3
  - CLI_OPTIONS_BEFORE_COMMAND
  - MISSING_COMMANDS_OR_OPTIONS_AT_CONSTRUCTION
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*' 
  environment: 
    NODE_ENV: production
 
functions:
  auth:
    handler: ./dist/apps/auth/main.handler
    events:
      - http:
          method: ANY
          path: /auth
      - http:
          method: ANY
          path: '/auth/{proxy+}'
  category:
    handler: ./dist/apps/category/main.handler
    events:
      - http:
          method: ANY
          path: /category
      - http:
          method: ANY
          path: '/category/{proxy+}'
  address:
    handler: ./dist/apps/address/main.handler
    events:
      - http:
          method: ANY
          path: /address
      - http:
          method: ANY
          path: '/address/{proxy+}'
  credit-card:
    handler: ./dist/apps/credit-card/main.handler
    events:
      - http:
          method: ANY
          path: /credit-card
      - http:
          method: ANY
          path: '/credit-card/{proxy+}'
  brand:
    handler: ./dist/apps/brand/main.handler
    events:
      - http:
          method: ANY
          path: /brand
      - http:
          method: ANY
          path: '/brand/{proxy+}'
  tag:
    handler: ./dist/apps/tag/main.handler
    events:
      - http:
          method: ANY
          path: /tag
      - http:
          method: ANY
          path: '/tag/{proxy+}'
  product:
    handler: ./dist/apps/product/main.handler
    events:
      - http:
          method: ANY
          path: /product
      - http:
          method: ANY
          path: '/product/{proxy+}'
  inventory:
    handler: ./dist/apps/inventory/main.handler
    events:
      - http:
          method: ANY
          path: /inventory
      - http:
          method: ANY
          path: '/inventory/{proxy+}'
  comment:
    handler: ./dist/apps/comment/main.handler
    events:
      - http:
          method: ANY
          path: /comment
      - http:
          method: ANY
          path: '/comment/{proxy+}'
  order:
    handler: ./dist/apps/order/main.handler
    events:
      - http:
          method: ANY
          path: /order
      - http:
          method: ANY
          path: '/order/{proxy+}'
  review:
    handler: ./dist/apps/review/main.handler
    events:
      - http:
          method: ANY
          path: /review
      - http:
          method: ANY
          path: '/review/{proxy+}'
  shipping:
    handler: ./dist/apps/shipping/main.handler
    events:
      - http:
          method: ANY
          path: /shipping
      - http:
          method: ANY
          path: '/shipping/{proxy+}'
  store:
    handler: ./dist/apps/store/main.handler
    events:
      - http:
          method: ANY
          path: /store
      - http:
          method: ANY
          path: '/store/{proxy+}'
  coupon:
    handler: ./dist/apps/coupon/main.handler
    events:
      - http:
          method: ANY
          path: /coupon
      - http:
          method: ANY
          path: '/coupon/{proxy+}'
 
  payment:
    handler: ./dist/apps/payment/main.handler
    events:
      - http:
          method: ANY
          path: /payment
      - http:
          method: ANY
          path: '/payment/{proxy+}'
 